### PR TITLE
Added Hugging Face demo link.

### PR DESCRIPTION
**Pull request by kadirnar**
- [X] Added Hugging Face demo link.

### CODE REVIEW

**Comment by edgarriba** [comment]
does it render well in notebooks ? if that's the case, really in favor /cc @NimaBoscarino

**Comment by NimaBoscarino** [comment]
The embedding doesn't look like it works, at least when I try it in Google Colab. Adding the "Hugging Face Spaces" badge looks good to me, but for the embedded demo I would recommend doing that over on the other repo, in https://github.com/kornia/kornia/blob/master/docs/source/applications/image_stitching.rst

**Comment by edgarriba** [comment]
i agree with @NimaBoscarino -- take inspiration from https://github.com/kornia/kornia/pull/1876

**Comment by kadirnar** [comment]
Hi @edgarriba,
I took [this repo ](https://github.com/kornia/tutorials/pull/32)as an example.

Can you check?

**Pull request merged**
