### PR TITLE
Fix/tutorials execution ci

### PR DESCRIPTION
**Pull request by ducha-aiki**
Follow up on https://github.com/kornia/tutorials/pull/65

### CODE REVIEW

**Comment by edgarriba** [comment]
@ducha-aiki did something change in kornia_moons ?

**Comment by ducha-aiki** [comment]
@edgarriba no. And it works locally for my python 3.10 env.
We discussed that in slack
https://kornia.slack.com/archives/C0102FPN884/p1694997707987449

**Comment by johnnv1** [comment]
we will need a new version of kornia moons with a hotfix for this move-on

**Comment by johnnv1** [comment]
mpl still mad about the same issue 🤔

**Review by johnnv1 — APPROVED** [review]

**Pull request merged**
