### PR TITLE
Update geometric_transforms.ipynb

### PR DESCRIPTION
**Pull request by YanivHollander**
I fixed two typos. I guess that since the file is a Jupiter notebook its shows as if I made a huge amount of changes. I couldn't find a way on GitHub to reflect the true nature of this change list!

### CODE REVIEW

**Comment by edgarriba** [comment]
@YanivHollander how did you do the changes ? in principle if you only modify lets say some typos the diff file should be small

**Comment by edgarriba** [comment]
Did you follow the standard process of forking repo, modify, etc ? if the checkout is through what I described before the diff should show only the changes applies to that patch.

**Comment by YanivHollander** [comment]
I actually followed this exact procedure, with the result of a huge list of changes. My changes are really minor, and could maybe integrated directly in the master branch:

1) The word design is spelled incorrectly in the BONUS section (design!). 
2) The word any appears twice in box [11].

**Review by edgarriba — APPROVED** [review]

**Comment by edgarriba** [comment]
Thanks!

**Pull request merged**
