### PR TITLE
Praj/edge detection demo

### PR DESCRIPTION
**Pull request by p-mishra1**
[#53](https://github.com/kornia/kornia/issues/53#issue-401715507) 
Hugging sapce demo and embedded app in the jupyter notebook.

### CODE REVIEW

**Comment by edgarriba** [comment]
@p-mishra1 the pull request should be opened to kornia main library in 
 https://github.com/kornia/kornia/blob/master/docs/source/filters.rst

**Comment by kadirnar** [comment]
It's great. You can use this code for Hugging Face logo.  What do you think @NimaBoscarino?

Example: 

Input:
```
<a href="https://huggingface.co/spaces/kornia/Image-Stitching"><img src="https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-blue.svg" alt="pypi version"></a>
```
Output:
<a href="https://huggingface.co/spaces/kornia/Image-Stitching">pypi version</a>

**Comment by p-mishra1** [comment]
> It's great. You can use this code for Hugging Face logo. What do you think @NimaBoscarino?
> 
> Example:
> 
> Input:
> 
> ```
> <a href="https://huggingface.co/spaces/kornia/Image-Stitching">pypi version</a>
> ```
> 
> Output: [pypi version](https://huggingface.co/spaces/kornia/Image-Stitching)
> 
> This is how I did it for the Colab notebook. #33

this is looking good @kadirnar I will add that in the tutorial, 
so should we keep both the app embedded in the notebook and a demo link button as you suggested int the tutorial.




> @p-mishra1 the pull request should be opened to kornia main library in https://github.com/kornia/kornia/blob/master/docs/source/filters.rst

I will raise a PR there on kornia repo as well.




> Awesome! Could you join the Kornia organization? https://huggingface.co/kornia And do you mind if I transfer your Space on Hugging Face to the Kornia organization?
> 
> I think the demo could also be linked or embedded here: https://kornia.readthedocs.io/en/latest/filters.html#edge-detection, on the other repo. I think you could just do it on this file: https://github.com/kornia/kornia/blob/master/docs/source/filters.rst

I have joined the kornia org on HF, and yes you can transfer the ownership of the HF space no issues.

**Comment by NimaBoscarino** [comment]
I think having the badge in the notebook would be okay, depends on @edgarriba's preference. But as he mentioned, the pull request should be moved over to the other repo. Otherwise, great job with the space!

**Comment by edgarriba** [comment]
the badge in the notebook is fine but for consistency the gradio app in the main docs, similar to
https://github.com/kornia/kornia/pull/1876

**Comment by p-mishra1** [comment]
@edgarriba removed the app [app has already been merged into the main docs] and added the badge.
we can merge this also if everything looks fine.

**Comment by edgarriba** [comment]
awesome !! this looks very cool!

**Pull request merged**
